baseURL = 'https://lmnlnlmns.org'
languageCode = 'en-us'
title = 'from seagull to...'
theme = 'paperesque'
buildDrafts = true

[params]
sidebar = true  

[[params.topmenu]]
name = "about"
url = "about/"

[[params.topmenu]]
name = "life projects"
url = "life-projects/"

[[params.topmenu]]
name = "subscribe"
url = "subscribe/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
page = ["HTML", "droplist"]
