baseURL = '/'
languageCode = 'en-us'
title = 'from seagull to...'
theme = 'paperesque'

# Hugo版本配置
[module]
  [module.hugoVersion]
    min = "0.110.0"
    max = ""
    extended = false

[params]
display_section = "posts"  
sidebar = true  

[[params.topmenu]]
name = "about"
url = "about/"

[[params.topmenu]]
name = "life projects"
url = "life-projects/"

[[params.topmenu]]
name = "subscribe"
url = "subscribe/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
